services:
  sportbuddies-app-eureka-server:
    image: sportbuddiesapp-be-eureka:0.0.1
    container_name: SportBuddiesApp-Be-Eureka-Server
    restart: always
    build:
       context: ../../../SportBuddiesApp-Be/SportBuddiesApp-Be-Eureka
       dockerfile: ./Dockerfile
    ports:
      - "8761:8761"
    networks:
      - sportbuddies-network

  sportbuddies-app-be-oauth:
    image: sportbuddiesapp-be-oauth:0.0.1
    container_name: SportBuddiesApp-Be-Oauth
    restart: always
    build:
      context: ../../../SportBuddiesApp-Be/SportBuddiesApp-Be-Oauth
      dockerfile: ./Dockerfile
    ports:
      - "9000:9000"
      - "8453:8453"
    volumes:
      - C:/SportBuddies_repository/SportBuddiesApp-Be-Oauth/dev/config:/repo-oauth
    environment:
      IP_HOST: sportbuddies-app-be-oauth
      BBDD_DOCKER: 192.168.0.22:3306
      EUREKA_DOCKER: SportBuddiesApp-Be-Eureka-Server
      MAVEN_OPTS: "-Pdev" 
    depends_on:
      - sportbuddies-app-eureka-server     
    networks:
      - sportbuddies-network

  sportbuddies-app-be-gateway:
    image: sportbuddiesapp-be-gateway:0.0.1
    container_name: SportBuddiesApp-Be-Gateway
    restart: always
    build:
      context: ../../../SportBuddiesApp-Be/SportBuddiesApp-Be-Gateway
      dockerfile: ./Dockerfile
    ports:
      - "8090:8090"
    volumes:
      - C:/SportBuddies_repository/SportBuddiesApp-Be-Gateway/dev/config:/repo-gateway
    environment:
      IP_HOST: sportbuddies-app-be-oauth
      BBDD_DOCKER: 192.168.0.22:3306
      EUREKA_DOCKER: SportBuddiesApp-Be-Eureka-Server
      MAVEN_OPTS: "-Pdev"
    depends_on:
      - sportbuddies-app-eureka-server
      - sportbuddies-app-be-oauth
    networks:
      - sportbuddies-network

  sportbuddies-app-main:
    image: sportbuddiesapp-be-main:0.0.1
    container_name: SportBuddiesApp-Be-Main
    restart: always
    build:
      context: C:/workspace_sportbuddies_be/SportBuddiesApp-Be/SportBuddiesApp-Be-Main
      dockerfile: ./Dockerfile
    ports:
      - "8100:8100"
    volumes:
      - C:/SportBuddies_repository/SportBuddiesApp-Be-Main/dev/config:/repo-main
    environment:
      BBDD_DOCKER: 192.168.0.22:3306
      EUREKA_DOCKER: SportBuddiesApp-Be-Eureka-Server
      MAVEN_OPTS: "-Pdev"
    depends_on:
      - sportbuddies-app-be-gateway
    networks:
      - sportbuddies-network

networks:
  sportbuddies-network:
    driver: bridge