version: '3.8'
services:
  eureka-server:
    image: sportbuddiesapp-be-eureka:0.0.1
    container_name: SportBuddiesApp-Be-Eureka-Server
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "8761:8761"
    networks:
      - sportbuddies-network
networks:
  sportbuddies-network:
    driver: bridge
