spring:  
  security:
    oauth2:
      resourceserver:
        # Ruta donde se va a validar el toquen (SportBuddiesApp-Be-Oauth)
        jwt:
          issuer-uri: "http://127.0.0.1:9000"
      client:
        registration:
          client-be:
            provider: spring
            client-id: gateway-app
            client-secret: 12345
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8090/authorized"
            scope:
              - openid
              - profile
            client-name: client-be
        provider:
          spring:
            issuer-uri: "http://127.0.0.1:9000"