spring:
  security:
    oauth2:
      resourceserver:
        # Ruta donde se va a validar el toquen (SportBuddiesApp-Be-Oauth)
        jwt:
          issuer-uri: "http://127.0.0.1:9000"
      client:
        registration:
          client-app:
            # Proveedor para iniciar el login
            provider: spring
            # Nombre del cliente-id que hemos indicando dentro de la clase SecurityConfig.java (SportBuddiesApp-Be-Oauth)
            client-id: gateway-app
            # Passwrod del cliente-id que hemos indicando dentro de la clase SecurityConfig.java (SportBuddiesApp-Be-Oauth)
            client-secret: 12345
            authorization-grant-type: authorization_code
            # EndPoint donde está configurado el servicio REST AutorizacionController.class (SportBuddiesApp-Be-Gateway) 
            redirect-uri: "http://127.0.0.1:8090/authorized"
            # Los roles que 
            scope:
              - openid
              - profile
              #- read
              #- write
            # Nombre del cliente que vamosa registrar (client-app) ubicado en la linea 10
            client-name: client-app
        # Configuracion del proveedor
        provider:
          spring:
            issuer-uri: "http://127.0.0.1:9000"