services:
  sportbuddies-app-be-oauth:
    image: sportbuddiesapp-be-oauth:0.0.1
    container_name: SportBuddiesApp-Be-Oauth
    build:
      context: C:/workspace_sportbuddies_be/SportBuddiesApp-Be/SportBuddiesApp-Be-Oauth
      dockerfile: ./Dockerfile
    ports:
      - "9000:9000"
      - "8453:8453"
    volumes:
      - C:/SportBuddies_repository/SportBuddiesApp-Be-Oauth/dev/config:/repo-oauth
    environment:
      BBDD_DOCKER: host.docker.internal
      EUREKA_DOCKER: 192.168.0.22:3306  
    networks:
      - sportbuddies-network

networks:
  sportbuddies-network:
    driver: bridge
